FROM tensorflow/tensorflow:latest-py3
MAINTAINER RyujiKawazoe

WORKDIR /

RUN apt-get update
RUN apt-get install -y git

# mecabの本体インストール
RUN git clone https://github.com/taku910/mecab.git
WORKDIR mecab/mecab
RUN [ "./configure", "--enable-utf8-only"]
RUN make
RUN make check
RUN make install

# mecabのインストールチェック
RUN ldconfig
RUN ldconfig -p | grep /usr/local/lib

# 辞書のインストール

WORKDIR /mecab/mecab-ipadic
RUN [ "./configure", "--with-charset=utf8"]
RUN make
RUN make install
#
# WORKDIR /
#
RUN pip install keras
RUN pip install sklearn
RUN pip install scipy
RUN pip install pandas
RUN pip install matplotlib
RUN pip install seaborn
RUN pip install h5py
RUN pip install mecab-python3
RUN pip install gensim

RUN apt-get install -y language-pack-ja
RUN update-locale LANG=ja_JP.UTF-8

ENV LANG ja_JP.UTF-8

WORKDIR /
